services:
  booksync:
    build: .
    container_name: booksync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=BookSync
      - BOOKSYNC_DATA_DIR=/config/booksync
      - PORT=3005
    volumes:
      - ./config:/config
      - ${DOWNLOADS_PATH:-./downloads}:/downloads
    ports:
      - ${WEBTOP_PORT:-3010}:3000 # Webtop HTTP
      - 3001:3001 # Webtop HTTPS
      - ${PORT:-3005}:3005 # BookSync Companion API
    restart: unless-stopped
