services:
  booksync:
    build: .
    container_name: booksync
    environment:
      - TZ=Etc/UTC
      - PORT=3000
      - BOOKSYNC_DATA_DIR=/config
      - BOOKSYNC_APP_PATH=/app
    volumes:
      - ./config:/config
      - ${DOWNLOADS_PATH:-./downloads}:/downloads
    ports:
      - ${BOOKSYNC_PORT:-3015}:3000
    restart: unless-stopped
